### ISSUE TITLE
Calling ./fetch-tor-list.sh more than once gives error

### ISSUE THREAD

**Issue by ghost** [aaronkaplan/torexitnodes_simple#4] opened 2019-08-08 12:32 UTC
`./fetch-tor-list.sh` does not remove old data, so executing it more than once (daily as the readme suggests) will give errors:

```
ERROR:  duplicate key value violates unique constraint "idx_node_combined"
DETAIL:  Key (node_id, ip, exit_address_ts, id_nodetype)=(0011BD2485AD45D984EC4159C88FC066E5E3300E, 162.247.74.201, 2019-08-08 09:12:18+02, 1) already exists.
```

**Comment by aaronkaplan** [comment] 2019-08-08 13:23
> On 08.08.2019, at 14:32, Wagner <notifications@github.com> wrote:
> 
> ./fetch-tor-list.sh does not remove old data, so executing it more than once (daily as the readme suggests) will give errors:
> 
> ERROR:  duplicate key value violates unique constraint "idx_node_combined"
> DETAIL:  Key (node_id, ip, exit_address_ts, id_nodetype)=(0011BD2485AD45D984EC4159C88FC066E5E3300E, 162.247.74.201, 2019-08-08 09:12:18+02, 1) already exists.
> 

works as intended. It's to be seen as a warning message. The INSERTs for the other rows continue. Just duplicate data does not get inserted twice.

Hard to catch these messages in .sh scripts. Sounds like it's easier to try: catch this in python then... hm... I'll keep this open for now. But really it's just cosmetics right now.

a.

**Comment by aaronkaplan** [comment] 2019-08-08 15:14
closing via #7. May be re-opened if we have a better idea

**Closed as completed by aaronkaplan** 2019-08-08 15:14 UTC
Labels: enhancement
